# German translations for vigilo-correlator.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-correlator
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-correlator 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 12:29+0100\n"
"PO-Revision-Date: 2011-11-22 10:52+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/twisted/plugins/vigilo_correlator.py:36
msgid "The topology has been reloaded."
msgstr "Die Topologie wurde erneut geladen."

#: src/twisted/plugins/vigilo_correlator.py:53
msgid ""
"Could not set signal handlers. The correlator may not be able to shutdown"
" cleanly"
msgstr ""
"Signalhandler konnte nicht eingestellt werden. Es kann sein, dass der "
"Korrelator nicht sauber herunterfahren kann"

#: src/vigilo/correlator/correvent.py:81
#, python-format
msgid ""
"Ignoring event #%(idevent)d on (%(host)r, %(service)r) as requested by "
"the correlation rules"
msgstr ""

#: src/vigilo/correlator/correvent.py:144
#, python-format
msgid ""
"Ignoring request to update correlated event %r: a more recent update "
"already exists in the database"
msgstr ""

#: src/vigilo/correlator/correvent.py:149
#, python-format
msgid "Updating existing correlated event (%r)"
msgstr "Bestehendes korreliertes Ereignis (%r) aktualisieren"

#: src/vigilo/correlator/correvent.py:152
#, python-format
msgid "Got a reference to a non-existent correlated event (%r), adding as new"
msgstr ""
"Verweis auf ein nicht vorhandenes korreliertes Ereignis (%r), wird als "
"neu hinzugefügt"

#: src/vigilo/correlator/correvent.py:162
#, python-format
msgid "Raw event ignored. Reason: status = %r"
msgstr "Rohereignis ignoriert. Ursache: Status = %r"

#: src/vigilo/correlator/correvent.py:190
#, python-format
msgid ""
"Got a reference to a nonexistent correlated event (%r), skipping this "
"aggregate"
msgstr ""
"Verweis auf ein nicht vorhandenes korreliertes Ereignis (%r), Aggregat "
"wird übersprungen"

#: src/vigilo/correlator/correvent.py:241
msgid "Creating new correlated event"
msgstr "Neues korreliertes Ereignis wird erstellt"

#: src/vigilo/correlator/correvent.py:373
msgid "Sending correlated event to syslog"
msgstr "Korreliertes Ereignis wird an Syslog gesendet"

#: src/vigilo/correlator/db_insertion.py:58
#, python-format
msgid "Received request to add an event on HLS \"%s\""
msgstr "Anforderung zur Hinzufügung eines Ereignisses auf HLS \"%s\" erhalten"

#: src/vigilo/correlator/db_insertion.py:63
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), "
"skipping event"
msgstr ""
"Verweis auf ein nicht konfiguriertes Element (%(host)r, %(service)r) "
"erhalten, Ereignis übersprungen"

#: src/vigilo/correlator/db_insertion.py:95
#, python-format
msgid "Updating event %r"
msgstr "Ereignis %r wird aktualisiert"

#: src/vigilo/correlator/db_insertion.py:101
#, python-format
msgid ""
"Ignoring request to create a new event with state \"%s\" (nothing "
"alarming here)"
msgstr ""
"Anforderung zur Erstellung eines neuen Ereignisse mit Status \"%s\" wird "
"ignoriert (hier nicht bedenklich)"

#: src/vigilo/correlator/db_insertion.py:108
msgid "Creating new event"
msgstr "Neues Ereignis wird erstellt"

#: src/vigilo/correlator/db_insertion.py:111
msgid "Multiple matching events found, skipping."
msgstr "Mehrere entsprechende Ereignisse gefunden, überspringen."

#: src/vigilo/correlator/db_insertion.py:161
#, python-format
msgid "Got a reference to a non configured high-level service (%(service)r)"
msgstr ""
"Verweis auf einen nicht konfigurierten High-level-Service (%(service)r) "
"vorhanden"

#: src/vigilo/correlator/db_insertion.py:188
#, python-format
msgid ""
"Got a reference to a non configured item (%(host)r, %(service)r), "
"skipping state"
msgstr ""
"Verweis auf ein nicht konfiguriertes Element (%(host)r, %(service)r) "
"vorhanden, Status überspringen"

#: src/vigilo/correlator/db_insertion.py:253
#, python-format
msgid "Adding event #%(event)d (supitem #%(supitem)d) to aggregate #%(aggregate)d"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:272
#, python-format
msgid ""
"Event #%(event)d already belongs to aggregate #%(aggregate)d, refusing to"
" add it twice"
msgstr ""

#: src/vigilo/correlator/db_insertion.py:303
#, fuzzy, python-format
msgid "Merging aggregate #%(src)d into aggregate #%(dest)d"
msgstr "Aggregat #%(src)d und Aggregat #%(dest)d werden zusammengeführt"

#: src/vigilo/correlator/db_insertion.py:355
#: src/vigilo/correlator/db_insertion.py:360
msgid "Got a reference to a nonexistent aggregate, aborting"
msgstr "Verweis auf ein nicht existierendes Quell-Aggregat vorhanden, abbrechen"

#: src/vigilo/correlator/db_insertion.py:372
#, python-format
msgid ""
"Event #%(event)d (supitem #%(supitem)d) will be merged into aggregate "
"#%(aggregate)d"
msgstr ""

#: src/vigilo/correlator/handle_ticket.py:35
#, python-format
msgid ""
"handle_ticket: Trouble ticket message received. Timestamp = "
"%(timestamp)r. Impacted HLS = %(hls)r. Ticket id = %(ticket_id)r. "
"acknowledgement_status = %(ack_status)r. Message = %(message)r."
msgstr ""
"handle_ticket: Trouble-Ticket-Nachricht erhalten. Timestamp = "
"%(timestamp)r. Betroffene HLS = %(hls)r. Ticket id = %(ticket_id)r. "
"acknowledgement_status = %(ack_status)r. Nachricht = %(message)r."

#: src/vigilo/correlator/handle_ticket.py:57
#, python-format
msgid "handle_ticket: No matching trouble ticket found : %r"
msgstr "handle_ticket: Kein passendes Trouble Ticket gefunden: %r"

#: src/vigilo/correlator/handle_ticket.py:63
#, python-format
msgid "handle_ticket: Several events seem to be associated with this ticket : %r"
msgstr ""
"handle_ticket: Mehrere Ereignisse scheinen zu diesem Ticket : %r zu "
"gehören"

#: src/vigilo/correlator/handle_ticket.py:66
#, python-format
msgid ""
"handle_ticket: The event %(event_id)r is associated with the given ticket"
" (%(ticket_id)r)"
msgstr ""
"handle_ticket: Das Ereignis %(event_id)r gehört zu dem gegebenen Ticket "
"(%(ticket_id)r)"

#: src/vigilo/correlator/handle_ticket.py:88
#, python-format
msgid "handle_ticket: Got exception while updating event %r history"
msgstr ""
"handle_ticket: Ausnahme bei der Aktualisierung des Verlaufs des "
"Ereignisses %r "

#: src/vigilo/correlator/handle_ticket.py:92
#, python-format
msgid "handle_ticket: Event %r history updated successfully."
msgstr "handle_ticket: Verlauf des Ereignisses %r erfolgreich aktualisiert."

#: src/vigilo/correlator/memcached_connection.py:62
#, fuzzy, python-format
msgid "Connected to memcached (%s)"
msgstr "Verbindung zum MemcacheD Server (%s) wird hergestellt..."

#: src/vigilo/correlator/memcached_connection.py:79
#, fuzzy, python-format
msgid "Connecting to memcached server (%s)..."
msgstr "Verbindung zum MemcacheD Server (%s) wird hergestellt..."

#: src/vigilo/correlator/memcached_connection.py:88
#, python-format
msgid "Connection to memcached (%(conn)s) lost: %(reason)s"
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:101
#, python-format
msgid "Connection to memcached (%(conn)s) failed: %(reason)s"
msgstr ""

#: src/vigilo/correlator/memcached_connection.py:231
#, python-format
msgid "Trying to set value '%(value)s' for key '%(key)s' (transaction=%(txn)r)."
msgstr ""
"Versucht den Wert '%(value)s' für Schlüssel '%(key)s' einzustellen "
"(transaction=%(txn)r)."

#: src/vigilo/correlator/memcached_connection.py:274
#, python-format
msgid "Trying to get the value of the key '%(key)s' (transaction=%(txn)r)."
msgstr ""
"Versucht, den Wert von Schlüssel '%(key)s' zu erhalten "
"(transaction=%(txn)r)."

#: src/vigilo/correlator/memcached_connection.py:307
#, python-format
msgid "Trying to delete the key '%(key)s' (transaction=%(txn)r)."
msgstr "Versucht, den Schlüssel '%(key)s' zu löschen (transaction=%(txn)r)."

#: src/vigilo/correlator/registry.py:59
#, python-format
msgid ""
"Rule %(name)s (%(class)s) has already been registered, ignoring attempt "
"to re-register it."
msgstr ""
"Regel %(name)s (%(class)s) wurde bereits registriert, der Versuch, sie "
"erneut zu registrieren, wird ignoriert."

#: src/vigilo/correlator/registry.py:68
#, python-format
msgid "The rule %(depended)r must be loaded before %(dependent)r."
msgstr "Regel %(depended)r muss vor %(dependent)r geladen werden."

#: src/vigilo/correlator/registry.py:77
#, python-format
msgid "Successfully registered rule %r"
msgstr "Erfolgreich registrierte Regel %r"

#: src/vigilo/correlator/registry.py:142
msgid ""
"Singleton has already been instanciated, ignoring attempt to create a new"
" instance."
msgstr ""
"Singleton wurde bereits instanziiert, der Versuch eine neue Instanz zu "
"erstellen wird ignoriert."

#: src/vigilo/correlator/registry.py:183
#, python-format
msgid "Not a valid rule name \"%s\""
msgstr "Nicht ein gültiger Regelname \"%s\""

#: src/vigilo/correlator/registry.py:189
#, python-format
msgid "Unable to load rule \"%(name)s\" (%(class)s)"
msgstr "Unfähig, die Regel \"%(name)s\" (%(class)s) zu laden"

#: src/vigilo/correlator/actors/executor.py:85
#, python-format
msgid "Rule %(rule_name)s timed out"
msgstr "Regel %(rule_name)s abgelaufen"

#: src/vigilo/correlator/actors/rule_dispatcher.py:142
#, python-format
msgid "Unable to contact the database: %s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:187
#, python-format
msgid "Skipping unrecognized item (%s)"
msgstr "Unbekanntes Element (%s) wird übersprungen"

#: src/vigilo/correlator/actors/rule_dispatcher.py:193
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:218
msgid "Received invalid XMPP item ID (None)"
msgstr "Ungültige XMPP Element ID (None) erhalten"

#: src/vigilo/correlator/actors/rule_dispatcher.py:232
msgid "Error while modifying the ticket"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:244
msgid "Error while retrieving supervised item ID"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:260
msgid ""
"The rule "
"'vigilo.correlator_enterprise.rules.hls_deps:HighLevelServiceDepsRule' "
"must be loaded for computation orders to be handled properly."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:270
#: src/vigilo/correlator/actors/rule_dispatcher.py:325
msgid ""
"The connection to memcached timed out. The message will be handled once "
"more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:345
msgid "Inserting state"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:347
msgid "Error while saving state"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:366
msgid "Inserting an entry in the HLS history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:368
msgid "Error while adding an entry in the HLS history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:373
msgid "Inserting an entry in the history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:375
msgid "Error while adding an entry in the history"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:402
msgid "Actual correlation"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:438
#, python-format
msgid "Correlation process ended (%.4fs)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:458
msgid "Handling correlation results"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:482
#, python-format
msgid ""
"Error while saving the correlated event (%s). The message will be handled"
" once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:513
#, python-format
msgid "Correlation failed for message #%(id)s (%(payload)s)"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:534
#, python-format
msgid ""
"Unable to store correlated alert for message #%(id)s (%(payload)s) : "
"%(error)s"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:558
msgid "Connection lost, stopping rule runners pool"
msgstr ""

#: src/vigilo/correlator/actors/rule_dispatcher.py:598
#, python-format
msgid "%s. The message will be handled once more."
msgstr ""

#: src/vigilo/correlator/actors/rule_runner.py:36
#, python-format
msgid ""
"Got an exception while running rule \"%(rule)s\". Running the correlator "
"in the foreground (service vigilo-correlator debug) may help "
"troubleshooting (%(error)s)"
msgstr ""
"Ausnahme während der Ausführung der Regel \"%(rule)s\". Ausführen der "
"Korrelator im Vordergrund (service vigilo-correlator debug) kann "
"Problemlösungen helfen (%(error)s)"

#: src/vigilo/correlator/rules/SetPriority.py:102
#, python-format
msgid ""
"The priority for the alert on (%(hostname)r, %(servicename)r) is "
"%(newprio)r (old: %(oldprio)r)."
msgstr ""

#: src/vigilo/correlator/rules/example.py:36
#, python-format
msgid "id %(id)s payload %(payload)s"
msgstr "id %(id)s Nutzlast %(payload)s"

#: src/vigilo/correlator/rules/svc_on_host_down.py:58
msgid "Host is down"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:60
#, python-format
msgid "Setting %d services to UNKNOWN"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:125
#, python-format
msgid "Unsupported transition: %(from)s -> %(to)s"
msgstr ""

#: src/vigilo/correlator/rules/svc_on_host_down.py:135
#, python-format
msgid "Asking Nagios for updates on %d services"
msgstr ""
